# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Disable rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_cast
  - force_try
  - force_unwrapping

# Enable opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# File paths to exclude
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - Build
  - .swiftpm
  - CampusMenuIOS # Exclude old folder

# Rules configuration
type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 100
  error: 200

type_name:
  min_length: 3
  max_length: 50

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

reporter: "xcode"
